{
 "title": "New dashboard Copy",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "따릉이 상태 지도",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 23, "w": 15, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  \"parkingBikeTotCnt\",\n  \"stationLatitude\",\n  \"stationLongitude\",\n  \"stationName\"\nFROM bike_tb\nWHERE\n  $__timeFilter(ts)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "텅 빈 곳",
   "type": "grafana-worldmap-panel",
   "description": "주차된 따릉이가 없는 곳",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  \"stationName\",\n  \"parkingBikeTotCnt\",\n  \"stationLatitude\",\n  \"stationLongitude\"\nFROM bike_tb\nWHERE\n  $__timeFilter(ts) AND\n  \"parkingBikeTotCnt\" = 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "텅 빈 곳 리스트",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  \"stationName\",\n  \"parkingBikeTotCnt\"\nFROM bike_tb\nWHERE\n  $__timeFilter(ts) and\n  \"parkingBikeTotCnt\" = 0\nORDER BY 1"
    }
   ]
  }
 ]
}