{
 "title": "IOT_Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "description": "집, 서울의 실시간 온도",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(created_time),\n  temp as seoul\nFROM\n  iot_tb\nWHERE\n  $__timeFilter(created_time) AND device = 'seoul'\n"
    },
    {
     "rawSql": "SELECT\n  $__time(created_time),\n  temp as home\nFROM\n  iot_tb\nWHERE\n  $__timeFilter(created_time) AND device = 'home'\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "description": "집, 서울의 실시간 습도",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(created_time),\n  humd as seoul\nFROM\n  iot_tb\nWHERE\n  $__timeFilter(created_time) AND device = 'seoul'\n"
    },
    {
     "rawSql": "SELECT\n  $__time(created_time),\n  humd as home\nFROM\n  iot_tb\nWHERE\n  $__timeFilter(created_time) AND device = 'home'\n"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "description": "집, 서울의 실시간 기압",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(created_time),\n  pres as seoul\nFROM\n  iot_tb\nWHERE\n  $__timeFilter(created_time) AND device = 'seoul'\n"
    },
    {
     "rawSql": "SELECT\n  $__time(created_time),\n  pres as home\nFROM\n  iot_tb\nWHERE\n  $__timeFilter(created_time) AND device = 'home'\n"
    }
   ]
  },
  {
   "title": "Average temp",
   "type": "gauge",
   "description": "평균 온도",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_time,$__interval),\n  avg(temp) AS \"Temp\"\nFROM iot_tb\nWHERE\n  $__timeFilter(created_time)\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Average humd",
   "type": "gauge",
   "description": "평균 습도",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_time,$__interval),\n  avg(humd) AS \"Humd\"\nFROM iot_tb\nWHERE\n  $__timeFilter(created_time)\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Average pres",
   "type": "gauge",
   "description": "평균 기압",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_time,$__interval),\n  avg(pres) AS \"Pres\"\nFROM iot_tb\nWHERE\n  $__timeFilter(created_time)\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "수집 데이터",
   "type": "table",
   "description": "수집 데이터",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_time AS \"time\",\n  temp,\n  humd,\n  pres\nFROM iot_tb\nWHERE\n  $__timeFilter(created_time)\nORDER BY time desc"
    }
   ]
  }
 ]
}