{
 "title": "Words_Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "수집 데이터",
   "type": "table",
   "description": "수집 데이터",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_time AS \"time\",\n  author,\n  text,\n  number_of_words,\n  length\nFROM words_tb\nWHERE\n  $__timeFilter(created_time)\nORDER BY created_time desc"
    }
   ]
  },
  {
   "title": "총 작성글 수 (지난 5분)",
   "type": "stat",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\n  FROM words_tb\n WHERE $__timeFilter(created_time)"
    }
   ]
  },
  {
   "title": "작성글 수 (지난 5분)",
   "type": "stat",
   "description": "유저별 작성글 수 (지난 5분간)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) AS JHLeeeMe\nFROM words_tb\nWHERE\n  $__timeFilter(created_time) AND\n  author = 'JHLeeeMe'\nGROUP BY \n  author"
    },
    {
     "rawSql": "SELECT\n  count(*) AS first_user\nFROM words_tb\nWHERE\n  $__timeFilter(created_time) AND\n  author = 'first_user'\nGROUP BY \n  author"
    },
    {
     "rawSql": "SELECT\n  count(*) AS second_user\nFROM words_tb\nWHERE\n  $__timeFilter(created_time) AND\n  author = 'second_user'\nGROUP BY \n  author"
    },
    {
     "rawSql": "SELECT\n  count(*) AS third_user\nFROM words_tb\nWHERE\n  $__timeFilter(created_time) AND\n  author = 'third_user'\nGROUP BY \n  author"
    }
   ]
  }
 ]
}